eigen_type('EigenFrame').
eigen_type('EigenFragment').
eigen_type('Draw').

eigen_type('LinearLayout').
eigen_type('Button'). 
eigen_type('CheckBox').
eigen_type('Define').
eigen_type('EditText').
eigen_type('HorizontalLine').
eigen_type('HtmlView').
eigen_type('ImageView').
eigen_type('ListView').
eigen_type('PopupHtmlView').
eigen_type('PopupTextView').
eigen_type('RadioButton').
eigen_type('Spinner').
eigen_type('Switch').
eigen_type('TextView').
eigen_type('ToastMessage').
eigen_type('ToggleButton').
eigen_type('Variable').
eigen_type('VerticalLine').
eigen_type('WebView').
%eigen_type('Cache'). 
%eigen_type('ConstraintLayout').
%eigen_type('RelativeLayout').
%eigen_type('RubyScript').
eigen_type('ActionList').
eigen_type('AlertDialog').
eigen_type('Clone').
eigen_type('JavaScript').
eigen_type('PopupScreen').
eigen_type('SecureFtp').
eigen_type('SecureShell').
eigen_type('SelectDialog').
eigen_type('UrlRequest').


action('ActionList').
action('AlertDialog').
%action('Cache'). 
action('Clone').
action('Define').
action('JavaScript').
action('ListView').
action('PopupHtmlView').
action('PopupScreen').
action('PopupTextView').
action('SecureFtp').
action('SecureShell').
action('SelectDialog').
action('ToastMessage').
action('UrlRequest').
action('Variable').
action('VerticalLine').
%action('RubyScript').

async('ActionList').
async('AlertDialog').
async('Clone').
async('ListView').
async('PopupHtmlView').
async('PopupScreen').
async('PopupTextView').
async('SecureFtp').
async('SecureShell').
async('SelectDialog').
async('ToastMessage').
async('UrlRequest').

layout_container('Define').
layout_container('LinearLayout').
layout_container('ListView').
layout_container('PopupScreen').
layout_container('SecureFtp').
layout_container('SecureShell').
layout_container('UrlRequest').
%layout_container('ConstraintLayout').
%layout_container('RelativeLayout').
layout_container('ActionList').
layout_container('Clone').

layout_component('Button'). 
layout_component('CheckBox').
layout_component('Define').
layout_component('EditText').
layout_component('HorizontalLine').
layout_component('HtmlView').
layout_component('ImageView').
layout_component('JavaScript').
layout_component('LinearLayout').
layout_component('ListView').
layout_component('PopupHtmlView').
layout_component('PopupScreen').
layout_component('PopupTextView').
layout_component('RadioButton').
layout_component('SecureFtp').
layout_component('SecureShell').
layout_component('SelectDialog').
layout_component('Spinner').
layout_component('Switch').
layout_component('TextView').
layout_component('ToastMessage').
layout_component('ToggleButton').
layout_component('UrlRequest').
layout_component('Variable').
layout_component('VerticalLine').
layout_component('WebView').
%layout_component('Cache'). 
%layout_component('ConstraintLayout').
%layout_component('RelativeLayout').
%layout_component('RubyScript').
layout_component('ActionList').
layout_component('AlertDialog').
layout_component('Clone').

visible_component('Button'). 
visible_component('CheckBox').
visible_component('EditText').
visible_component('HorizontalLine').
visible_component('HtmlView').
visible_component('ImageView').
visible_component('LinearLayout').
visible_component('ListView').
visible_component('RadioButton').
visible_component('SecureFtp').
visible_component('SecureShell').
visible_component('Spinner').
visible_component('Switch').
visible_component('TextView').
visible_component('ToggleButton').
visible_component('UrlRequest').
visible_component('VerticalLine').
visible_component('WebView').
%visible_component('ConstraintLayout').
%visible_component('RelativeLayout').
%visible_component('RubyScript').
visible_component('ActionList').
visible_component('Clone').

on_complete('ActionList').
on_complete('ListView').
on_complete('SecureFtp').
on_complete('SecureShell').
on_complete('UrlRequest').
on_complete('RubyScript').

has_title('AlertDialog').
has_title('PopupScreen').
has_title('PopupHtmlView').
has_title('PopupTextView').
has_title('SelectDialog').

can_have_icon('EigenFragment').
can_have_icon('AlertDialog').
can_have_icon('PopupScreen').
can_have_icon('SelectDialog').
can_have_icon('SelectDialog').
can_have_icon('CheckBox').
can_have_icon('Switch').
can_have_icon('Button').
can_have_icon('SelectDialog').
can_have_icon('ToggleButton').

can_source_url('EigenFragment').
can_source_url('PopupScreen').
can_source_url('WebView').
can_source_url('HtmlView').
can_source_url('EditText').
can_source_url('ImageView').
can_source_url('UrlRequest').
can_source_url('TextView').
can_source_url('ListView').

can_source_ssh('SecureShell').
%can_source_ssh('HtmlView').
can_source_ssh('TextView').
can_source_ssh('EditText').
can_source_ssh('PopupHtmlView').
can_source_ssh('PopupTextView').

can_source_sftp('EditText').
can_source_sftp('TextView').
can_source_sftp('SecureFtp').
can_source_sftp('ListView').

put_ancestor(A, B) :-
    write('{\"'),write(A),write(' is an ancestor of '),write(B),write('\"}'),nl.
